/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const AccountModel: typeof import('../models/AccountModel.js')['default']
  const AuthRefreshRequest: typeof import('../models/AuthRefreshRequest.js')['default']
  const AuthRequest: typeof import('../models/AuthRequest.js')['default']
  const AuthUser: typeof import('../models/AuthUser.js')['AuthUser']
  const AutoRefreshAuth: typeof import('../composables/AutoRefreshAuth.js')['AutoRefreshAuth']
  const DisableLayoutEscapeKey: typeof import('../composables/DisableLayoutEscapeKey.js')['DisableLayoutEscapeKey']
  const Draggable: typeof import('@vueuse/core')['useDraggable']
  const EffectScope: typeof import('vue')['EffectScope']
  const EventModel: typeof import('../models/EventModel.js')['default']
  const IAuditable: typeof import('../models/IAuditable.js')['IAuditable']
  const IsDuplicateMessage: typeof import('../helpers/global.js')['IsDuplicateMessage']
  const KeyboardListeners: typeof import('../composables/KeyboardListeners.js')['KeyboardListeners']
  const MessageModel: typeof import('../models/MessageModel.js')['MessageModel']
  const PageItem: typeof import('../models/PagerModel.js')['PageItem']
  const PagedList: typeof import('../models/PagerModel.js')['PagedList']
  const PagerModel: typeof import('../models/PagerModel.js')['PagerModel']
  const RedirectToPage: typeof import('../composables/RedirectToPage.js')['RedirectToPage']
  const Result: typeof import('../models/PagerModel.js')['Result']
  const SearchForAccount: typeof import('../models/PagerModel.js')['SearchForAccount']
  const SearchForUser: typeof import('../models/PagerModel.js')['SearchForUser']
  const SearchModel: typeof import('../models/PagerModel.js')['SearchModel']
  const SetHtmlHeadBody: typeof import('../composables/SetHtmlHeadBody.js')['SetHtmlHeadBody']
  const UserModel: typeof import('../models/UserModel.js')['default']
  const accountValidator: typeof import('../helpers/validators.js')['accountValidator']
  const addDays: typeof import('../helpers/global.js')['addDays']
  const apiCall: typeof import('../composables/ApiCall.js')['apiCall']
  const apiDelete: typeof import('../composables/ApiCall.js')['apiDelete']
  const apiFormPost: typeof import('../composables/ApiCall.js')['apiFormPost']
  const apiGet: typeof import('../composables/ApiCall.js')['apiGet']
  const apiPost: typeof import('../composables/ApiCall.js')['apiPost']
  const authRequestValidator: typeof import('../helpers/validators.js')['authRequestValidator']
  const authSignupValidator: typeof import('../helpers/validators.js')['authSignupValidator']
  const computed: typeof import('vue')['computed']
  const constants: typeof import('../datalists/constants.js')['constants']
  const createApp: typeof import('vue')['createApp']
  const customRef: typeof import('vue')['customRef']
  const dateFormat: typeof import('../helpers/global.js')['dateFormat']
  const dateISO: typeof import('../helpers/global.js')['dateISO']
  const dateTimeFormat: typeof import('../helpers/global.js')['dateTimeFormat']
  const dateTimeISO: typeof import('../helpers/global.js')['dateTimeISO']
  const defineAsyncComponent: typeof import('vue')['defineAsyncComponent']
  const defineComponent: typeof import('vue')['defineComponent']
  const defineLoader: typeof import('vue-router/auto')['defineLoader']
  const definePage: typeof import('unplugin-vue-router/runtime')['_definePage']
  const defineStore: typeof import('pinia')['defineStore']
  const effectScope: typeof import('vue')['effectScope']
  const filterTypesList: typeof import('../datalists/filterTypesList.js')['filterTypesList']
  const getCurrentInstance: typeof import('vue')['getCurrentInstance']
  const getCurrentScope: typeof import('vue')['getCurrentScope']
  const h: typeof import('vue')['h']
  const hasKeys: typeof import('../helpers/global.js')['hasKeys']
  const inject: typeof import('vue')['inject']
  const isProxy: typeof import('vue')['isProxy']
  const isReactive: typeof import('vue')['isReactive']
  const isReadonly: typeof import('vue')['isReadonly']
  const isRef: typeof import('vue')['isRef']
  const logJson: typeof import('../helpers/global.js')['logJson']
  const markRaw: typeof import('vue')['markRaw']
  const nextTick: typeof import('vue')['nextTick']
  const numbersOnly: typeof import('../helpers/global.js')['numbersOnly']
  const onActivated: typeof import('vue')['onActivated']
  const onBeforeMount: typeof import('vue')['onBeforeMount']
  const onBeforeRouteLeave: typeof import('vue-router/auto')['onBeforeRouteLeave']
  const onBeforeRouteUpdate: typeof import('vue-router/auto')['onBeforeRouteUpdate']
  const onBeforeUnmount: typeof import('vue')['onBeforeUnmount']
  const onBeforeUpdate: typeof import('vue')['onBeforeUpdate']
  const onDeactivated: typeof import('vue')['onDeactivated']
  const onErrorCaptured: typeof import('vue')['onErrorCaptured']
  const onMounted: typeof import('vue')['onMounted']
  const onRenderTracked: typeof import('vue')['onRenderTracked']
  const onRenderTriggered: typeof import('vue')['onRenderTriggered']
  const onScopeDispose: typeof import('vue')['onScopeDispose']
  const onServerPrefetch: typeof import('vue')['onServerPrefetch']
  const onUnmounted: typeof import('vue')['onUnmounted']
  const onUpdated: typeof import('vue')['onUpdated']
  const onWatcherCleanup: typeof import('vue')['onWatcherCleanup']
  const pageSizeList: typeof import('../datalists/pageSizeList.js')['pageSizeList']
  const provide: typeof import('vue')['provide']
  const reactive: typeof import('vue')['reactive']
  const readonly: typeof import('vue')['readonly']
  const ref: typeof import('vue')['ref']
  const resolveComponent: typeof import('vue')['resolveComponent']
  const rolesList: typeof import('../datalists/roleList.js')['rolesList']
  const sampleCalendarEvents: typeof import('../datalists/sampleCalendarEvents.js')['sampleCalendarEvents']
  const shallowReactive: typeof import('vue')['shallowReactive']
  const shallowReadonly: typeof import('vue')['shallowReadonly']
  const shallowRef: typeof import('vue')['shallowRef']
  const storeToRefs: typeof import('pinia')['storeToRefs']
  const timeFormat: typeof import('../helpers/global.js')['timeFormat']
  const toRaw: typeof import('vue')['toRaw']
  const toRef: typeof import('vue')['toRef']
  const toRefs: typeof import('vue')['toRefs']
  const toValue: typeof import('vue')['toValue']
  const triggerRef: typeof import('vue')['triggerRef']
  const unref: typeof import('vue')['unref']
  const usPhoneFormat: typeof import('../helpers/global.js')['usPhoneFormat']
  const usStatesList: typeof import('../datalists/usStatesList.js')['usStatesList']
  const useAccountsStore: typeof import('../stores/AccountsStore.js')['useAccountsStore']
  const useAlertControl: typeof import('../composables/UseAlertControl.js')['useAlertControl']
  const useAppStore: typeof import('../stores/AppStore.js')['useAppStore']
  const useAttrs: typeof import('vue')['useAttrs']
  const useAuthStore: typeof import('../stores/AuthStore.js')['useAuthStore']
  const useCalendarStore: typeof import('../stores/CalendarStore.js')['useCalendarStore']
  const useChatHub: typeof import('../composables/UseChatHub.js')['useChatHub']
  const useChatStore: typeof import('../stores/ChatStore.js')['useChatStore']
  const useClipboard: typeof import('@vueuse/core')['useClipboard']
  const useConfirmControl: typeof import('../composables/UseConfirmControl.js')['useConfirmControl']
  const useCssModule: typeof import('vue')['useCssModule']
  const useCssVars: typeof import('vue')['useCssVars']
  const useDebounceFn: typeof import('@vueuse/core')['useDebounceFn']
  const useId: typeof import('vue')['useId']
  const useImagesStore: typeof import('../stores/ImagesStore.js')['useImagesStore']
  const useLocalStorage: typeof import('@vueuse/core')['useLocalStorage']
  const useModel: typeof import('vue')['useModel']
  const usePagedList: typeof import('../composables/UsePagedList.js')['usePagedList']
  const usePagedList2: typeof import('../composables/UsePagedList2.js')['usePagedList2']
  const useRoute: typeof import('vue-router/auto')['useRoute']
  const useRouter: typeof import('vue-router/auto')['useRouter']
  const useScrollLock: typeof import('../composables/useScrollLock.js')['useScrollLock']
  const useSignalR: typeof import('../composables/UseSignalR.js')['useSignalR']
  const useSlots: typeof import('vue')['useSlots']
  const useTemplateRef: typeof import('vue')['useTemplateRef']
  const useToastStore: typeof import('../stores/ToastStore.js')['useToastStore']
  const useUnsavedGuard: typeof import('../composables/UseUnsavedGuard.js')['useUnsavedGuard']
  const useUsersStore: typeof import('../stores/UsersStore.js')['useUsersStore']
  const useVuelidate: typeof import('@vuelidate/core')['useVuelidate']
  const useWindowSize: typeof import('@vueuse/core')['useWindowSize']
  const userValidator: typeof import('../helpers/validators.js')['userValidator']
  const watch: typeof import('vue')['watch']
  const watchEffect: typeof import('vue')['watchEffect']
  const watchPostEffect: typeof import('vue')['watchPostEffect']
  const watchSyncEffect: typeof import('vue')['watchSyncEffect']
  const weekdayFull: typeof import('../helpers/global.js')['weekdayFull']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { AccountModel } from '../models/AccountModel.js'
  import('../models/AccountModel.js')
  // @ts-ignore
  export type { AuthRefreshRequest } from '../models/AuthRefreshRequest.js'
  import('../models/AuthRefreshRequest.js')
  // @ts-ignore
  export type { AuthRequest } from '../models/AuthRequest.js'
  import('../models/AuthRequest.js')
  // @ts-ignore
  export type { EventModel } from '../models/EventModel.js'
  import('../models/EventModel.js')
  // @ts-ignore
  export type { UserModel } from '../models/UserModel.js'
  import('../models/UserModel.js')
}
// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly AccountModel: UnwrapRef<typeof import('../models/AccountModel.js')['default']>
    readonly AuthRefreshRequest: UnwrapRef<typeof import('../models/AuthRefreshRequest.js')['default']>
    readonly AuthRequest: UnwrapRef<typeof import('../models/AuthRequest.js')['default']>
    readonly AuthUser: UnwrapRef<typeof import('../models/AuthUser.js')['AuthUser']>
    readonly AutoRefreshAuth: UnwrapRef<typeof import('../composables/AutoRefreshAuth.js')['AutoRefreshAuth']>
    readonly DisableLayoutEscapeKey: UnwrapRef<typeof import('../composables/DisableLayoutEscapeKey.js')['DisableLayoutEscapeKey']>
    readonly Draggable: UnwrapRef<typeof import('@vueuse/core')['useDraggable']>
    readonly EffectScope: UnwrapRef<typeof import('vue')['EffectScope']>
    readonly EventModel: UnwrapRef<typeof import('../models/EventModel.js')['default']>
    readonly IAuditable: UnwrapRef<typeof import('../models/IAuditable.js')['IAuditable']>
    readonly IsDuplicateMessage: UnwrapRef<typeof import('../helpers/global.js')['IsDuplicateMessage']>
    readonly KeyboardListeners: UnwrapRef<typeof import('../composables/KeyboardListeners.js')['KeyboardListeners']>
    readonly MessageModel: UnwrapRef<typeof import('../models/MessageModel.js')['MessageModel']>
    readonly PageItem: UnwrapRef<typeof import('../models/PagerModel.js')['PageItem']>
    readonly PagedList: UnwrapRef<typeof import('../models/PagerModel.js')['PagedList']>
    readonly PagerModel: UnwrapRef<typeof import('../models/PagerModel.js')['PagerModel']>
    readonly RedirectToPage: UnwrapRef<typeof import('../composables/RedirectToPage.js')['RedirectToPage']>
    readonly Result: UnwrapRef<typeof import('../models/PagerModel.js')['Result']>
    readonly SearchForAccount: UnwrapRef<typeof import('../models/PagerModel.js')['SearchForAccount']>
    readonly SearchForUser: UnwrapRef<typeof import('../models/PagerModel.js')['SearchForUser']>
    readonly SearchModel: UnwrapRef<typeof import('../models/PagerModel.js')['SearchModel']>
    readonly SetHtmlHeadBody: UnwrapRef<typeof import('../composables/SetHtmlHeadBody.js')['SetHtmlHeadBody']>
    readonly UserModel: UnwrapRef<typeof import('../models/UserModel.js')['default']>
    readonly accountValidator: UnwrapRef<typeof import('../helpers/validators.js')['accountValidator']>
    readonly addDays: UnwrapRef<typeof import('../helpers/global.js')['addDays']>
    readonly apiCall: UnwrapRef<typeof import('../composables/ApiCall.js')['apiCall']>
    readonly apiDelete: UnwrapRef<typeof import('../composables/ApiCall.js')['apiDelete']>
    readonly apiFormPost: UnwrapRef<typeof import('../composables/ApiCall.js')['apiFormPost']>
    readonly apiGet: UnwrapRef<typeof import('../composables/ApiCall.js')['apiGet']>
    readonly apiPost: UnwrapRef<typeof import('../composables/ApiCall.js')['apiPost']>
    readonly authRequestValidator: UnwrapRef<typeof import('../helpers/validators.js')['authRequestValidator']>
    readonly authSignupValidator: UnwrapRef<typeof import('../helpers/validators.js')['authSignupValidator']>
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly createApp: UnwrapRef<typeof import('vue')['createApp']>
    readonly customRef: UnwrapRef<typeof import('vue')['customRef']>
    readonly dateFormat: UnwrapRef<typeof import('../helpers/global.js')['dateFormat']>
    readonly dateISO: UnwrapRef<typeof import('../helpers/global.js')['dateISO']>
    readonly dateTimeFormat: UnwrapRef<typeof import('../helpers/global.js')['dateTimeFormat']>
    readonly dateTimeISO: UnwrapRef<typeof import('../helpers/global.js')['dateTimeISO']>
    readonly defineAsyncComponent: UnwrapRef<typeof import('vue')['defineAsyncComponent']>
    readonly defineComponent: UnwrapRef<typeof import('vue')['defineComponent']>
    readonly defineLoader: UnwrapRef<typeof import('vue-router/auto')['defineLoader']>
    readonly definePage: UnwrapRef<typeof import('unplugin-vue-router/runtime')['_definePage']>
    readonly defineStore: UnwrapRef<typeof import('pinia')['defineStore']>
    readonly effectScope: UnwrapRef<typeof import('vue')['effectScope']>
    readonly filterTypesList: UnwrapRef<typeof import('../datalists/filterTypesList.js')['filterTypesList']>
    readonly getCurrentInstance: UnwrapRef<typeof import('vue')['getCurrentInstance']>
    readonly getCurrentScope: UnwrapRef<typeof import('vue')['getCurrentScope']>
    readonly h: UnwrapRef<typeof import('vue')['h']>
    readonly hasKeys: UnwrapRef<typeof import('../helpers/global.js')['hasKeys']>
    readonly inject: UnwrapRef<typeof import('vue')['inject']>
    readonly isProxy: UnwrapRef<typeof import('vue')['isProxy']>
    readonly isReactive: UnwrapRef<typeof import('vue')['isReactive']>
    readonly isReadonly: UnwrapRef<typeof import('vue')['isReadonly']>
    readonly isRef: UnwrapRef<typeof import('vue')['isRef']>
    readonly logJson: UnwrapRef<typeof import('../helpers/global.js')['logJson']>
    readonly markRaw: UnwrapRef<typeof import('vue')['markRaw']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly numbersOnly: UnwrapRef<typeof import('../helpers/global.js')['numbersOnly']>
    readonly onActivated: UnwrapRef<typeof import('vue')['onActivated']>
    readonly onBeforeMount: UnwrapRef<typeof import('vue')['onBeforeMount']>
    readonly onBeforeRouteLeave: UnwrapRef<typeof import('vue-router/auto')['onBeforeRouteLeave']>
    readonly onBeforeRouteUpdate: UnwrapRef<typeof import('vue-router/auto')['onBeforeRouteUpdate']>
    readonly onBeforeUnmount: UnwrapRef<typeof import('vue')['onBeforeUnmount']>
    readonly onBeforeUpdate: UnwrapRef<typeof import('vue')['onBeforeUpdate']>
    readonly onDeactivated: UnwrapRef<typeof import('vue')['onDeactivated']>
    readonly onErrorCaptured: UnwrapRef<typeof import('vue')['onErrorCaptured']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onRenderTracked: UnwrapRef<typeof import('vue')['onRenderTracked']>
    readonly onRenderTriggered: UnwrapRef<typeof import('vue')['onRenderTriggered']>
    readonly onScopeDispose: UnwrapRef<typeof import('vue')['onScopeDispose']>
    readonly onServerPrefetch: UnwrapRef<typeof import('vue')['onServerPrefetch']>
    readonly onUnmounted: UnwrapRef<typeof import('vue')['onUnmounted']>
    readonly onUpdated: UnwrapRef<typeof import('vue')['onUpdated']>
    readonly onWatcherCleanup: UnwrapRef<typeof import('vue')['onWatcherCleanup']>
    readonly pageSizeList: UnwrapRef<typeof import('../datalists/pageSizeList.js')['pageSizeList']>
    readonly provide: UnwrapRef<typeof import('vue')['provide']>
    readonly reactive: UnwrapRef<typeof import('vue')['reactive']>
    readonly readonly: UnwrapRef<typeof import('vue')['readonly']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly resolveComponent: UnwrapRef<typeof import('vue')['resolveComponent']>
    readonly rolesList: UnwrapRef<typeof import('../datalists/roleList.js')['rolesList']>
    readonly sampleCalendarEvents: UnwrapRef<typeof import('../datalists/sampleCalendarEvents.js')['sampleCalendarEvents']>
    readonly shallowReactive: UnwrapRef<typeof import('vue')['shallowReactive']>
    readonly shallowReadonly: UnwrapRef<typeof import('vue')['shallowReadonly']>
    readonly shallowRef: UnwrapRef<typeof import('vue')['shallowRef']>
    readonly storeToRefs: UnwrapRef<typeof import('pinia')['storeToRefs']>
    readonly timeFormat: UnwrapRef<typeof import('../helpers/global.js')['timeFormat']>
    readonly toRaw: UnwrapRef<typeof import('vue')['toRaw']>
    readonly toRef: UnwrapRef<typeof import('vue')['toRef']>
    readonly toRefs: UnwrapRef<typeof import('vue')['toRefs']>
    readonly toValue: UnwrapRef<typeof import('vue')['toValue']>
    readonly triggerRef: UnwrapRef<typeof import('vue')['triggerRef']>
    readonly unref: UnwrapRef<typeof import('vue')['unref']>
    readonly usPhoneFormat: UnwrapRef<typeof import('../helpers/global.js')['usPhoneFormat']>
    readonly usStatesList: UnwrapRef<typeof import('../datalists/usStatesList.js')['usStatesList']>
    readonly useAccountsStore: UnwrapRef<typeof import('../stores/AccountsStore.js')['useAccountsStore']>
    readonly useAlertControl: UnwrapRef<typeof import('../composables/UseAlertControl.js')['useAlertControl']>
    readonly useAppStore: UnwrapRef<typeof import('../stores/AppStore.js')['useAppStore']>
    readonly useAttrs: UnwrapRef<typeof import('vue')['useAttrs']>
    readonly useAuthStore: UnwrapRef<typeof import('../stores/AuthStore.js')['useAuthStore']>
    readonly useCalendarStore: UnwrapRef<typeof import('../stores/CalendarStore.js')['useCalendarStore']>
    readonly useChatHub: UnwrapRef<typeof import('../composables/UseChatHub.js')['useChatHub']>
    readonly useChatStore: UnwrapRef<typeof import('../stores/ChatStore.js')['useChatStore']>
    readonly useClipboard: UnwrapRef<typeof import('@vueuse/core')['useClipboard']>
    readonly useConfirmControl: UnwrapRef<typeof import('../composables/UseConfirmControl.js')['useConfirmControl']>
    readonly useCssModule: UnwrapRef<typeof import('vue')['useCssModule']>
    readonly useCssVars: UnwrapRef<typeof import('vue')['useCssVars']>
    readonly useDebounceFn: UnwrapRef<typeof import('@vueuse/core')['useDebounceFn']>
    readonly useId: UnwrapRef<typeof import('vue')['useId']>
    readonly useImagesStore: UnwrapRef<typeof import('../stores/ImagesStore.js')['useImagesStore']>
    readonly useLocalStorage: UnwrapRef<typeof import('@vueuse/core')['useLocalStorage']>
    readonly useModel: UnwrapRef<typeof import('vue')['useModel']>
    readonly usePagedList2: UnwrapRef<typeof import('../composables/UsePagedList2.js')['usePagedList2']>
    readonly usePagedList: UnwrapRef<typeof import('../composables/UsePagedList.js')['usePagedList']>
    readonly useRoute: UnwrapRef<typeof import('vue-router/auto')['useRoute']>
    readonly useRouter: UnwrapRef<typeof import('vue-router/auto')['useRouter']>
    readonly useScrollLock: UnwrapRef<typeof import('../composables/useScrollLock.js')['useScrollLock']>
    readonly useSignalR: UnwrapRef<typeof import('../composables/UseSignalR.js')['useSignalR']>
    readonly useSlots: UnwrapRef<typeof import('vue')['useSlots']>
    readonly useTemplateRef: UnwrapRef<typeof import('vue')['useTemplateRef']>
    readonly useToastStore: UnwrapRef<typeof import('../stores/ToastStore.js')['useToastStore']>
    readonly useUnsavedGuard: UnwrapRef<typeof import('../composables/UseUnsavedGuard.js')['useUnsavedGuard']>
    readonly useUsersStore: UnwrapRef<typeof import('../stores/UsersStore.js')['useUsersStore']>
    readonly useVuelidate: UnwrapRef<typeof import('@vuelidate/core')['useVuelidate']>
    readonly useWindowSize: UnwrapRef<typeof import('@vueuse/core')['useWindowSize']>
    readonly userValidator: UnwrapRef<typeof import('../helpers/validators.js')['userValidator']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
    readonly watchPostEffect: UnwrapRef<typeof import('vue')['watchPostEffect']>
    readonly watchSyncEffect: UnwrapRef<typeof import('vue')['watchSyncEffect']>
    readonly weekdayFull: UnwrapRef<typeof import('../helpers/global.js')['weekdayFull']>
  }
}
