using coreApi.Models;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.OpenApi.Any;
using Microsoft.OpenApi.Models;
using Swashbuckle.AspNetCore.Swagger;
using Swashbuckle.AspNetCore.SwaggerGen;
using Swashbuckle.AspNetCore.SwaggerUI;
using System.Diagnostics;
using System.Runtime.InteropServices;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace coreApi.Helpers;

public static class SwaggerHelper 
{
	public static void AddMyCustomSwaggerGen(this IServiceCollection services)
	{
		services.AddSwaggerGen(AddMySwaggerGenOptions());
	}	

	public static void UseMyCustomSwagger(this WebApplication app, bool allEnvironments = true)
	{
		if (allEnvironments || app.Environment.IsDevelopment())
		{
			app.UseSwagger(MyUseSwaggerOptions());
			app.UseSwaggerUI(MyUseSwaggerUIOptions());
		}
	}

	// ==================================================================================

	private static Action<SwaggerGenOptions> AddMySwaggerGenOptions()
	{
		return options =>
		{
			options.SwaggerDoc("v1", new OpenApiInfo
			{
				Title		= "VueCore API",
				Version		= "v1",
				Description = "This VueCore API documentation is auto-generated by Swagger and can be enabled or disabled per environment. " +
							  "Because Swagger UI(Swashbuckle) is no longer included in default.NET 9+ Web API templates, it is added via NuGet." +
							  "Most endpoints require authorization—log in using 'Authenticate.Login' to obtain a Token." +
							  "Open the 'Authorize' dialog, paste the JWT token into the value field, then click 'Authorize'. " +
							  "Finally, close the dialog to begin making authorized API calls."
			});

			options.AddSecurityDefinition("Bearer",
				new OpenApiSecurityScheme()
				{
					In              = ParameterLocation.Header,
					Type            = SecuritySchemeType.ApiKey,
					Scheme          = JwtBearerDefaults.AuthenticationScheme,
					Name            = "Authorization",
					BearerFormat    = "JWT",
					Description     = "Use the Login endpoint to retrieve your authentication Token, and paste it into the value field below." +
									  "Click Authorize to complete the process.Your access to other endpoints will depend on your assigned user permissions."
				}
			);

			options.AddSecurityRequirement(new OpenApiSecurityRequirement {
				{
					new OpenApiSecurityScheme
					{
						Reference = new OpenApiReference
						{
							Type = ReferenceType.SecurityScheme,
							Id = "Bearer"
						}
					},
					Array.Empty<string>()
				}
			});

			// Create custom Swagger input values for example calls
			options.SchemaFilter<SwaggerExamplesHelper>();
		};
	}

	/// <summary>Update project Swagger options</summary>
	private static Action<SwaggerOptions> MyUseSwaggerOptions()
	{
		return options =>
		{
			options.RouteTemplate = "docs/{documentName}/docs.json";
			options.SerializeAsV2 = true;  // Required for DotNet 9 to work 
		};
	}

	/// <summary>Update project Swagger UI options and routes</summary>
	private static Action<SwaggerUIOptions> MyUseSwaggerUIOptions()
	{
		return options =>
		{
			options.RoutePrefix = "docs";

			options.EnableTryItOutByDefault();
			options.SwaggerEndpoint("/docs/v1/docs.json", "VueCore V1");
			options.EnableTryItOutByDefault();
			options.InjectStylesheet("/swagger-ui/custom.css");
			options.InjectJavascript("/swagger-ui/custom.js");
		};
	}
}
