export const examplesDataList =
    [
        { name: 'Accordian', example: 'AccordianExample', show: true, featured: false, type: '', order: 5},
        { name: 'Calendar', example: 'CalendarExample', show: true, featured: false, type: '', order: 5},
        { name: 'Checkers', example: 'CheckersExample', show: true, featured: true, type: '', order: 5},
        { name: 'Composables', example: 'ComposablesExample', show: true, featured: false, type: '', order: 5},
        { name: 'ContentEditor', example: 'ContentEditorExample', show: true, featured: false, type: '', order: 5},
        { name: 'Files', example: 'FilesExample', show: true, featured: false, type: '', order: 5},
        { name: 'Floater', example: 'FloaterExample', show: true, featured: false, type: '', order: 5},
        { name: 'Grid', example: 'GridExample', show: true, featured: false, type: '', order: 2},
        { name: 'ImageCropper', example: 'ImageCropperExample', show: true, featured: false, type: '', order: 5},
        { name: 'Inputs', example: 'InputsExample', show: true, featured: true, type: '', order: 1},
        { name: 'Intro', example: 'IntroExample', show: true, featured: true, type: '', order: 0},
        { name: 'JsonTree', example: 'JsonTreeExample', show: true, featured: false, type: '', order: 5},
        { name: 'ListIndexButton', example: 'ListIndexButtonExample', show: true, featured: false, type: '', order: 5},
        { name: 'Misc', example: 'MiscExample', show: false, featured: false, type: '', order: 5},
        { name: 'MultiSelect', example: 'MultiSelectExample', show: true, featured: false, type: '', order: 5},
        { name: 'TabsBar', example: 'TabsBarExample', show: true, featured: false, type: '', order: 5},
        { name: 'TabsControl', example: 'Tabsexample', show: true, featured: false, type: '', order: 5},
        { name: 'TabsOverflowControl', example: 'TabsOverflowexample', show: true, featured: false, type: '', order: 5},
        { name: 'Wizard', example: 'WizardExample', show: true, featured: false, type: '', order: 5},
    ]